application/design_application/forms.py
# -*- coding: utf-8 -*-
from wtforms import Form, StringField, SelectField, TextAreaField
from wtforms.validators import *


class DesignApplicationForm(Form):
    status = SelectField('申请状态', choices=[('新申请', '新申请'), ('申请通过', '申请通过'), ('申请不通过', '申请不通过')])
    dl_file_memo = TextAreaField('备注')

application/product/forms.py
# -*- coding: utf-8 -*-
import wtforms
from wtforms.validators import *

application/__init__.py
# -*- coding: utf-8 -*-
import os
from flask import Flask, g, render_template, redirect, url_for, request, flash
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from .utils import num2moneyformat

from .config import config
from flask_cache import Cache

import logging

app = Flask(__name__)
app.config.from_object(config[os.getenv('FLASK_ENV') or 'default'])
db = SQLAlchemy(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "backstage_management.account_login"

bcrypt = Bcrypt(app)
cache = Cache(app, config={'CACHE_TYPE': 'simple'})

from .content.views import content

app.register_blueprint(content, url_prefix='/content')
from .product.views import product

app.register_blueprint(product, url_prefix='/product')
from .order_manage.views import order_manage

app.register_blueprint(order_manage, url_prefix='/order_manage')
from .inventory.views import inventory

app.register_blueprint(inventory, url_prefix='/inventory')
from .wechat.views import wechat

app.register_blueprint(wechat, url_prefix='/wechat')
from .design_application.views import design_application

app.register_blueprint(design_application, url_prefix='/design_application')
from .project_report.views import project_report

app.register_blueprint(project_report, url_prefix='/project_report')
from .organization.views import organization

app.register_blueprint(organization, url_prefix='/organization')
from .web_access_log.views import web_access_log

app.register_blueprint(web_access_log, url_prefix='/web_access_log')

from .backstage_management.views import backstage_management

app.register_blueprint(backstage_management, url_prefix='/backstage_management')

from .inventory.api import load_products, load_skus, load_inventories_by_code

app.add_template_global(load_products)
app.add_template_global(load_skus)
app.add_template_global(load_inventories_by_code)
app.add_template_global(len)
app.add_template_global(int)
app.add_template_global(str)
app.add_template_global(num2moneyformat)


@app.before_first_request
def setup_logging():
    if not app.debug:
        # In production mode, add log handler to sys.stderr.
        app.logger.addHandler(logging.StreamHandler())
        app.logger.setLevel(logging.INFO)
        app.logger.info("RUN ENV : [%s]" % os.getenv('FLASK_ENV'))


@app.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404


@app.errorhandler(500)
def internal_server_error(error):
    return render_template('500.html'), 500


@app.route('/')
def root():
    return redirect(url_for('mobile_index'))


@app.route('/admin')
def admin():
    return redirect(url_for('backstage_management.index'))

application/content/views.py
# -*- coding: utf-8 -*-
import os, datetime
from flask import Blueprint, flash, g, redirect, render_template, request, url_for, jsonify
from flask_login import current_user

from .. import app, db, cache
from ..helpers import object_list, save_upload_file, delete_file, clip_image
from ..models import Content, ContentCategory, ContentClassification, ContentClassificationOption
from ..models import Material, MaterialApplication, MaterialApplicationContent, LogisticsCompanyInfo
from ..wechat.models import WechatCall
from .forms import *

content = Blueprint('content', __name__, template_folder='templates')
content_image_size = (379, 226)


# url -- /content/..
@content.route('/')
def root():
    return redirect(url_for('content.index'))


@content.route('/index/<int:category_id>/')
def index(category_id):
    category = ContentCategory.query.get_or_404(category_id)
    query = Content.query.filter(Content.category_id == category_id)
    if request.args.get('name'):
        query = query.filter(Content.name.contains(request.args.get('name')))
    contents = query.order_by(Content.created_at.desc())
    return object_list('content/index.html', contents, paginate_by=20, category=category)


@content.route('/new/<int:category_id>', methods=['GET', 'POST'])
def new(category_id):
    if request.method == 'POST':
        form = ContentForm(request.form)
        if form.validate():
            option_ids = request.form.getlist('option_ids[]') 
            request_options = ContentClassificationOption.query.filter(ContentClassificationOption.id.in_(option_ids))
            content = form.save(Content(category_id=category_id))
            content.append_options(request_options)
            image_links = []
            if request.files:
                for param in request.files:
                    if 'image_file' in param and request.files.get(param):
                        index = int(param.rsplit('_', 1)[1])
                        if len(image_links) < index + 1:
                            for i in range(index+1-len(image_links)):
                                image_links.append('')
                        image_path = save_upload_file(request.files.get(param))
                        if image_path:
                            clip_image((app.config['APPLICATION_DIR'] + image_path), size=content_image_size)
                        image_links[index] = image_path
            content.image_links = image_links
            content.save
            flash('Content "{name}" created successfully.'.format(name=content.name), 'success')
            return redirect(url_for('content.index', category_id=category_id))
    else:
        category = ContentCategory.query.get_or_404(category_id)
        options = category.options
        form = ContentForm()
    return render_template('content/new.html', form=form, options=options, category=category)


@content.route('/<int:id>')
def show(id):
    content = Content.query.get_or_404(id)
    return render_template('content/show.html', content=content)


@content.route('/<int:id>/edit', methods=['GET', 'POST'])
def edit(id):
    content = Content.query.get_or_404(id)
    options = content.category.options
    if request.method == 'POST':
        form = ContentForm(request.form)
        if form.validate():
            option_ids = request.form.getlist('option_ids[]')
            request_options = ContentClassificationOption.query.filter(ContentClassificationOption.id.in_(option_ids))
            content = form.save(content)
            content.update_options(request_options)
            image_links = list(content.image_links)
            if request.files:
                for param in request.files:
                    if 'image_file' in param and request.files.get(param):
                        index = int(param.rsplit('_', 1)[1])
                        if len(image_links) < index + 1:
                            for i in range(index+1-len(image_links)):
                                image_links.append('')
                        image_path = save_upload_file(request.files.get(param))
                        if image_path:
                            clip_image((app.config['APPLICATION_DIR'] + image_path), size=content_image_size)
                            delete_file(image_links[index])
                        image_links[index] = image_path
            content.image_links = image_links
            content.save
            flash('Content "{name}" has been updated.'.format(name=content.name), 'success')
            return redirect(url_for('content.index', category_id=content.category_id))
    else:
        form = ContentForm(obj = content)
    return render_template('content/edit.html', form=form, content=content, options=options)


@content.route('/<int:id>/delete', methods=['POST'])
def delete(id):
    content = Content.query.get_or_404(id)
    if request.method == 'POST':
        content.delete
        flash('Content "{name}" has been deleted.'.format(name=content.name), 'success')
        if request.args.get('back_url'):
            return redirect(request.args.get('back_url'))
        return redirect(url_for('content.category_index'))


# url -- /content/category/..
@content.route('/category/index')
def category_index():
    categories = ContentCategory.query.order_by(ContentCategory.created_at.asc())
    return render_template('content/category/index.html', categories=categories)


@content.route('/category/new', methods=['GET', 'POST'])
def category_new():
    if request.method == 'POST':
        form = ContentCategoryForm(request.form)
        if form.validate():
            category = form.save(ContentCategory())
            category.save
            flash('Content category "{name}" created successfully.'.format(name=category.name), 'success')
            return redirect(url_for('content.category_index'))
    else:
        form = ContentCategoryForm()
    return render_template('content/category/new.html', form = form)


@content.route('/category/<int:id>')
def category_show(id):
    category = ContentCategory.query.get_or_404(id)
    return render_template('content/category/show.html', category=category)


@content.route('/category/<int:id>/edit', methods=['GET', 'POST'])
def category_edit(id):
    category = ContentCategory.query.get_or_404(id)
    if request.method == 'POST':
        form = ContentCategoryForm(request.form)
        if form.validate():
            category = form.save(category)
            category.save
            flash('Content category "{name}" has been updated.'.format(name=category.name), 'success')
            return redirect(url_for('content.category_index'))
    else:
        form = ContentCategoryForm(obj=category)
    return render_template('content/category/edit.html', form=form, category=category)


@content.route('/category/<int:id>/delete', methods=['GET', 'POST'])
def category_delete(id):
    category = ContentCategory.query.get_or_404(id)
    if request.method == 'POST':
        category.delete_p
        flash('Content category "{name}" has been deleted.'.format(name=category.name), 'success')
        return redirect(url_for('content.category_index'))
    return render_template('content/category/delete.html', category=category)


# url -- /content/classification/..
@content.route('/classification/new/<int:category_id>', methods=['GET', 'POST'])
def classification_new(category_id):
    if request.method == 'POST':
        form = ContentClassificationForm(request.form)
        if form.validate():
            classification = form.save(ContentClassification(category_id=category_id))
            classification.save
            flash('Content classification "{name}" created successfully.'.format(name=classification.name), 'success')
            return redirect(url_for('content.category_show', id=category_id))
    else:
        form = ContentClassificationForm()
    return render_template('content/classification/new.html', form=form, category_id=category_id)


@content.route('/classification/<int:id>')
def classification_show(id):
    classification = ContentClassification.query.get_or_404(id)
    return render_template('content/classification/show.html', classification=classification)


@content.route('/classification/<int:id>/edit', methods=['GET', 'POST'])
def classification_edit(id):
    classification = ContentClassification.query.get_or_404(id)
    if request.method == 'POST':
        form = ContentClassificationForm(request.form)
        if form.validate():
            classification = form.save(classification)
            classification.save
            flash('Content Classification "{name}" has been updated.'.format(name=classification.name), 'success')
            return redirect(url_for('content.category_show', id=classification.category_id))
    else:
        form = ContentClassificationForm(obj=classification)
    return render_template('content/classification/edit.html', form=form, classification=classification)


@content.route('/classification/<int:id>/delete', methods=['GET', 'POST'])
def classification_delete(id):
    classification = ContentClassification.query.get_or_404(id)
    if request.method == 'POST':
        classification.delete_p
        flash('Content classification "{name}" has been deleted.'.format(name=classification.name), 'success')
        return redirect(url_for('content.category_show', id=classification.category_id))
    return render_template('content/classification/delete.html', classification=classification)


# url -- /content/option/..
@content.route('/option/new/<int:classification_id>', methods=['GET', 'POST'])
def option_new(classification_id):
    if request.method == 'POST':
        form = ContentClassificationOptionForm(request.form)
        if form.validate():
            option = form.save(ContentClassificationOption(classification_id=classification_id))
            option.save

application/design_application/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, flash, g, redirect, render_template, request, url_for, send_file
from flask_login import current_user
from flask.helpers import make_response
from .. import app, cache
from ..helpers import object_list, save_upload_file, delete_file
from ..models import DesignApplication, ProjectReport
from .forms import DesignApplicationForm
from ..wechat.models import WechatCall

design_application = Blueprint('design_application', __name__, template_folder='templates')


@design_application.route('/index')
def index():
    applications = DesignApplication.query.all()
    return render_template('design_application/index.html', applications=applications)


@design_application.route('/<int:id>/edit', methods=['GET', 'POST'])
def edit(id):
    application = DesignApplication.query.get_or_404(id)
    project_report = ProjectReport.query.filter_by(report_no=application.filing_no).first()
    if request.method == 'POST':
        form = DesignApplicationForm(request.form)
        form.populate_obj(application)
        if request.form.get('status') == '申请通过':
            if request.files.get('dl_file'):
                file_path = save_upload_file(request.files.get('dl_file'))
                if file_path:
                    if application.dl_file:
                        delete_file(application.dl_file)
                    application.dl_file = file_path
                else:
                    flash('%s文件格式不合法' % str(request.files.get('dl_file').filename), 'danger')
                    return redirect(url_for('design_application.index'))
            flash('申请通过 %s' % str(request.files.get('dl_file').filename), 'success')
        elif request.form.get('status') == '申请不通过':
            flash('申请不通过', 'warning')
        application.save
        cache.delete_memoized(current_user.get_new_design_application_num)
        WechatCall.send_template_to_user(str(application.applicant_id),
                                         "lW5jdqbUIcAwTF5IVy8iBzZM-TXMn1hVf9qWOtKZWb0",
                                         {
                                             "first": {
                                                 "value": "您的产品设计申请状态已更改",
                                                 "color": "#173177"
                                             },
                                             "keyword1": {
                                                 "value": application.filing_no,
                                                 "color": "#173177"
                                             },
                                             "keyword2": {
                                                 "value": application.status,
                                                 "color": "#173177"
                                             },
                                             "keyword3": {
                                                 "value": '',
                                                 "color": "#173177"
                                             },
                                             "remark": {
                                                 "value": "感谢您的使用！",
                                                 "color": "#173177"
                                             },
                                         },
                                         url_for('mobile_design_file', id=application.id)
                                         )
        return redirect(url_for('design_application.index'))
    else:
        form = DesignApplicationForm(obj=application)
    return render_template('design_application/edit.html', application=application, project_report=project_report,
                           form=form)


@design_application.route('/<int:id>/dl_file')
def dl_file(id):
    application = DesignApplication.query.get_or_404(id)
    response = make_response(send_file(app.config['APPLICATION_DIR'] + application.dl_file))
    response.headers['Content-Disposition'] = 'attachment; filename = %s' % application.dl_file.rsplit('/', 1)[1]
    return response


@design_application.route('/<int:id>/ul_file')
def ul_file(id):
    application = DesignApplication.query.get_or_404(id)
    response = make_response(send_file(app.config['APPLICATION_DIR'] + application.ul_file))
    response.headers['Content-Disposition'] = 'attachment; filename = %s' % application.ul_file.rsplit('/', 1)[1]
    return response

application/templates/content/category/edit.html
{% extends 'pc_base.html' %}
{% from 'macros/pc_partial.html' import sidebar with context %}
{% block main_content %}

{{ sidebar(active = 'file') }}
<div class="contents">
	<div class="contents-header">
		<div class="contents-header-img"><img class="full-img" src="/static/images/product.png" /></div>
		<p class="contents-header-p">编辑目录</p>
		<p class="contents-header-p text-sm">edit titles</p>
	</div>
	<div class="separator"><span></span></div>
	<div class="widget">
		<div class="widget_header">
			<h4 class="widget_header_title"><span class="glyphicon glyphicon-off"></span>&nbsp;&nbsp;&nbsp;编辑目录</h4>
		</div>

		<form action="{{ url_for('content.category_edit', id = category.id) }}" method="post">
			<div class="widget_contents padding-0">
				<div class="form-item">
					{% for field in form %}
					<span class="form-label">{{ field.label }}</span>{{ field(class = 'form-input form-control') }}
					{% endfor %}
				</div>
			</div>
			<div class="text-right top-gap-1">
				<a href="{{ url_for('content.category_index') }}" class="btn btn-default my-btn">返回</a>	
				<button type="submit" class="btn btn-default my-btn" data-disable-with="Please wait...">更新</button>
			</div>
		</form>

	</div>
</div>

{% endblock %}

application/templates/content/category/index.html
{% extends 'pc_base.html' %}
{% from 'macros/pc_partial.html' import sidebar with context %}
{% block main_content %}

{{ sidebar(active = 'file') }}
<div class="contents">
	<div class="contents-header">
		<div class="contents-header-img"><img class="full-img" src="/static/images/product.png" /></div>
		<p class="contents-header-p">目录列表</p>
		<p class="contents-header-p text-sm">content categories</p>
		<a class="new-one" href="{{ url_for('content.category_new') }}" title="新增目录"><span class="glyphicon glyphicon-plus"></span></a>
	</div>
	<div class="separator"><span></span></div>
	<div class="widget">
		<div class="widget_header">
			<h4 class="widget_header_title"><span class="glyphicon glyphicon-th-large"></span>
				&nbsp;&nbsp;&nbsp;<a>目录列表</a>
			</h4>
		</div>
		<div class="widget_contents padding-0">
			<table class="tables">
				<thead>
					<tr>
						<th>目录名称</th>
						<th>创建日期</th>
						<th>操作</th>
					</tr>
				</thead>
				<tbody>
				{% for category in categories %}
					<tr>
						<td>{{ category.name }}</td>
						<td>{{ category.created_at.strftime('%F %T') }}</td>
						<td>
							<a href="{{ url_for('content.index', category_id = category.id) }}" class="table-edit text-default"><span class="glyphicon glyphicon-folder-open"></span>&nbsp;&nbsp;内容列表</a>
							<a href="{{ url_for('content.category_show', id = category.id) }}" class="table-del text-success"><span class="glyphicon glyphicon-list"></span>&nbsp;&nbsp;目录管理</a>						
							<a class="table-edit text-info" href="{{ url_for('content.category_edit', id = category.id) }}"><span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;编辑</a>
							<form action="{{ url_for('content.category_delete', id=category.id) }}" method="post" style="display: inline;">
								<button type="submit" data-confirm="删除目录[ {{ category.name }} ]后, 将会一并删除其下的子目录, 确定删除吗？" data-confirmType="post" class="btn-link table-del" style="color: #843534; text-decoration: none; "><span class="glyphicon glyphicon-remove"></span>&nbsp;&nbsp;删除</button>
							</form>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>

{% endblock %}


		

application/templates/content/category/new.html
{% extends 'pc_base.html' %}
{% from 'macros/pc_partial.html' import sidebar with context %}
{% block main_content %}

{{ sidebar(active = 'file') }}
<div class="contents">
	<div class="contents-header">
		<div class="contents-header-img"><img class="full-img" src="/static/images/product.png" /></div>
		<p class="contents-header-p">新增目录</p>
		<p class="contents-header-p text-sm">new titles</p>
	</div>
	<div class="separator"><span></span></div>
	<div class="widget">
		<div class="widget_header">
			<h4 class="widget_header_title"><span class="glyphicon glyphicon-off"></span>&nbsp;&nbsp;&nbsp;新增目录</h4>
		</div>

		<form action="{{ url_for('content.category_new') }}" method="post">
			<div class="widget_contents padding-0">
				{% for field in form %}
					<div class="form-item">									
						<span class="form-label">{{ field.label }}</span>{{ field(class = 'form-input form-control') }}
					</div>
				{% endfor %}	
			</div>
			<div class="text-right top-gap-1">
				<a href="{{ url_for('content.category_index') }}" class="btn btn-default my-btn">返回</a>
				<button type="submit" class="btn btn-default my-btn" data-disable-with="Please wait...">提交</button>		
			</div>
		</form>

	</div>
</div>

{% endblock %}

application/templates/content/category/show.html
{% extends 'pc_base.html' %}
{% from 'macros/pc_partial.html' import sidebar with context %}
{% block main_content %}

{{ sidebar(active = 'file') }}
<div class="contents">
	<div class="contents-header">
		<div class="contents-header-img"><img class="full-img" src="/static/images/product.png" /></div>
		<p class="contents-header-p">次级目录列表</p>
		<p class="contents-header-p text-sm">list of classifications</p>
		<a class="new-one" href="{{ url_for('content.classification_new', category_id = category.id) }}"><span class="glyphicon glyphicon-plus"></span></a>
	</div>
	<div class="separator"><span></span></div>
	<div class="widget">
		<div class="widget_header">
			<h4 class="widget_header_title"><span class="glyphicon glyphicon-th-large"></span>
				&nbsp;&nbsp;&nbsp;<a href="{{ url_for('content.category_index') }}" class="text-muted">目录列表</a> >
				<a>{{ category.name }}</a>
			</h4>
		</div>
		<div class="widget_contents padding-0">
			<table class="tables">
				<thead>
					<tr>
						<th>名称</th>
						<th>创建日期</th>
						<th>操作</th>
					</tr>
				</thead>
				<tbody>
				{% for classification in category.classifications %}
				<tr>
					<td><a href="{{ url_for('content.classification_show', id = classification.id) }}" class="table-link">{{ classification.name }}</a></td>
					<td>{{ classification.created_at.strftime('%F %T') }}</td>
					<td>
						<a class="table-edit text-info" href="{{ url_for('content.classification_edit', id = classification.id) }}"><span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;编辑</a>
						<form action="{{ url_for('content.classification_delete', id = classification.id) }}" method="post" style="display: inline;">
							<button type="submit" data-confirm="删除目录[ {{ classification.name }} ]后, 将会一并删除其下的子目录, 确定删除吗？" data-confirmType="post" class="btn-link table-del" style="color: #843534; text-decoration: none; "><span class="glyphicon glyphicon-remove"></span>&nbsp;&nbsp;删除</button>
						</form>
					</td>
				</tr>								
				{% endfor %}
				</tbody>
			</table>
		</div>

		<div class="text-right top-gap-1">
			<a href="{{ url_for('content.category_index') }}" class="btn btn-default my-btn">返回上一级目录</a>
		</div>
	</div>
</div>

{% endblock %}