application/design_application/forms.py
# -*- coding: utf-8 -*-
from wtforms import Form, StringField, SelectField, TextAreaField
from wtforms.validators import *


class DesignApplicationForm(Form):
    status = SelectField('申请状态', choices=[('新申请', '新申请'), ('申请通过', '申请通过'), ('申请不通过', '申请不通过')])
    dl_file_memo = TextAreaField('备注')

application/product/forms.py
# -*- coding: utf-8 -*-
import wtforms
from wtforms.validators import *

application/__init__.py
# -*- coding: utf-8 -*-
import os
from flask import Flask, g, render_template, redirect, url_for, request, flash
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from .utils import num2moneyformat

from .config import config
from flask_cache import Cache

import logging

app = Flask(__name__)
app.config.from_object(config[os.getenv('FLASK_ENV') or 'default'])
db = SQLAlchemy(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "backstage_management.account_login"

bcrypt = Bcrypt(app)
cache = Cache(app, config={'CACHE_TYPE': 'simple'})

from .content.views import content

app.register_blueprint(content, url_prefix='/content')
from .product.views import product

app.register_blueprint(product, url_prefix='/product')
from .order_manage.views import order_manage

app.register_blueprint(order_manage, url_prefix='/order_manage')
from .inventory.views import inventory

app.register_blueprint(inventory, url_prefix='/inventory')
from .wechat.views import wechat

app.register_blueprint(wechat, url_prefix='/wechat')
from .design_application.views import design_application

app.register_blueprint(design_application, url_prefix='/design_application')
from .project_report.views import project_report

app.register_blueprint(project_report, url_prefix='/project_report')
from .organization.views import organization

app.register_blueprint(organization, url_prefix='/organization')
from .web_access_log.views import web_access_log

app.register_blueprint(web_access_log, url_prefix='/web_access_log')

from .backstage_management.views import backstage_management

app.register_blueprint(backstage_management, url_prefix='/backstage_management')

from .inventory.api import load_products, load_skus, load_inventories_by_code

app.add_template_global(load_products)
app.add_template_global(load_skus)
app.add_template_global(load_inventories_by_code)
app.add_template_global(len)
app.add_template_global(int)
app.add_template_global(str)
app.add_template_global(num2moneyformat)


@app.before_first_request
def setup_logging():
    if not app.debug:
        # In production mode, add log handler to sys.stderr.
        app.logger.addHandler(logging.StreamHandler())
        app.logger.setLevel(logging.INFO)
        app.logger.info("RUN ENV : [%s]" % os.getenv('FLASK_ENV'))


@app.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404


@app.errorhandler(500)
def internal_server_error(error):
    return render_template('500.html'), 500


@app.route('/')
def root():
    return redirect(url_for('mobile_index'))


@app.route('/admin')
def admin():
    return redirect(url_for('backstage_management.index'))

application/backstage_management/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for, session
from .. import app
from ..models import User, AuthorityOperation, WebpageDescribe
from .forms import AccountLoginForm, AccountForm
from ..forms import BaseCsrfForm
from flask_login import logout_user, login_user, current_user
from ..wechat.models import WechatCall, WechatUserInfo

backstage_management = Blueprint('backstage_management', __name__, template_folder='templates')


# 单个使用@login_required
# 访问页面是否登入拦截
@backstage_management.before_app_request
def login_check():
    # url_rule
    # app.logger.info("into login_check")

    # 图片加载 or 无匹配请求
    if request.endpoint == "static" or request.endpoint is None:
        if request.endpoint is None:
            app.logger.info("LOGIN_CHECK None?  request.path [%s] , [%s]" % (request.path, request.endpoint))
        pass
    # 网站root访问 移动端
    # 所有移动端页面
    # wechat.mobile_ 使用微信相关JS的移动端页面
    else:
        if request.endpoint == "root" or \
                request.endpoint.startswith("mobile_") or \
                request.endpoint.startswith("wechat.mobile_") or \
                request.path.startswith("/mobile/"):

            # 微信自动登入拦截 -- code只能使用一次,所以绑定界面不能拦截
            if not request.endpoint == 'wechat.mobile_user_binding' and request.args.get("code") is not None:
                app.logger.info("微信端code自动登入拦截 code[%s]" % request.args.get("code"))
                try:
                    openid = WechatCall.get_open_id_by_code(request.args.get("code"))
                    app.logger.info("微信端code自动登入拦截 openid[%s]" % openid)
                    wui = WechatUserInfo.query.filter_by(open_id=openid, is_active=True).first()
                    app.logger.info("微信端code自动登入拦截 wui记录[%s]" % wui)
                    if wui is not None:
                        exists_binding_user = User.query.filter_by(id=wui.user_id).first()
                        app.logger.info("微信端code自动登入拦截 user记录[%s]" % exists_binding_user)
                        if exists_binding_user is not None:
                            if current_user.is_authenticated and not exists_binding_user == current_user:
                                app.logger.info(
                                    "微信自动登入用户[%s],登出[%s]" % (exists_binding_user.nickname, current_user.nickname))
                                logout_user()
                            login_user(exists_binding_user)
                            app.logger.info("binding user login [%s] - [%s]" % (openid, exists_binding_user.nickname))
                except Exception as e:
                    app.logger.info("微信端code自动登入拦截异常[%s]" % e)
                    pass

            # 访问请求端的页面 不进行拦截
            if request.endpoint == "mobile_user_login" or request.endpoint == 'wechat.mobile_user_binding':
                pass
            # 未登入用户跳转登入界面
            elif not current_user.is_authenticated:
                app.logger.info("LOGIN_CHECK INTO MOBILE  request.path [%s] , [%s]" % (request.path, request.endpoint))
                # 后端界面
                flash("请登入后操作")
                session["login_next_url"] = request.path
                return redirect(url_for('mobile_user_login'))
            # 被禁止用户
            else:
                login_valid_errmsg = current_user.check_can_login()
                if not login_valid_errmsg == "":
                    flash(login_valid_errmsg)
                    logout_user()
                    return redirect(url_for('mobile_user_login'))
        # 其他与微信服务器交互接口 不进行登入判断
        elif request.endpoint.startswith("wechat."):
            # 微信
            pass
        # 后端管理界面
        else:
            # 访问请求端的页面 不进行拦截
            if request.endpoint == "backstage_management.account_login":
                # 后端登入界面
                pass
            # 未登入用户跳转登入界面
            elif not current_user.is_authenticated or current_user.user_or_origin != 3:
                app.logger.info("LOGIN_CHECK INTO BACK END request.path [%s] , [%s]" % (request.path, request.endpoint))
                # 后端界面
                flash("请登入后操作")
                session["login_next_url"] = request.path
                return redirect(url_for('backstage_management.account_login'))
            # 被禁止用户
            else:
                login_valid_errmsg = current_user.check_can_login()
                if not login_valid_errmsg == "":
                    flash(login_valid_errmsg)
                    logout_user()
                    return redirect(url_for('backstage_management.account_login'))

    return None


# 访问页面 是否有权限拦截
@backstage_management.before_app_request
def authority_check():
    # app.logger.info("into authority_check")
    if request.endpoint == "static" or request.endpoint is None \
            or current_user is None or not current_user.is_authenticated:
        pass
    else:
        if AuthorityOperation.is_authorized(current_user, request.endpoint, request.method) is False:
            flash("无权限登入页面 [%s] ,请确认" % WebpageDescribe.query.filter_by(endpoint=request.endpoint,
                                                                        method=request.method).first().describe)
            return redirect(url_for('backstage_management.index'))


@backstage_management.route('/index')
def index():
    app.logger.info("into index")
    form = AccountForm(obj=current_user, user_type=current_user.get_user_type_name(), meta={'csrf_context': session})
    if len(current_user.user_infos) == 0:
        pass
    else:
        ui = current_user.user_infos[0]
        form.name.data = ui.name
        form.address.data = ui.address
        form.phone.data = ui.telephone
        form.title.data = ui.title

    if current_user.sales_areas.first() is not None:
        form.sale_range.data = ",".join([s.name for s in current_user.sales_areas.all()])
    if current_user.departments.first() is not None:
        form.dept_ranges.data = ",".join([d.name for d in current_user.departments.all()])

    return render_template('backstage_management/index.html', form=form)


# -- login
# 需要区分pc or wechat ?
@backstage_management.route('/account/login', methods=['GET', 'POST'])
def account_login():
    if current_user.is_authenticated:
        if current_user.user_or_origin == 3:
            return redirect(url_for('backstage_management.index'))
        else:
            # 不运行前后端同时登入在一个WEB上
            app.logger.info("移动端用户[%s]自动登出,[%s][%s]" % (current_user.nickname, request.path, request.endpoint))
            logout_user()

    # app.logger.info("account_login [%s]" % request.args)
    if request.method == 'POST':
        try:
            form = AccountLoginForm(request.form, meta={'csrf_context': session})
            if form.validate() is False:
                raise ValueError(form.errors)

            # 后台只能员工登入
            user = User.login_verification(form.email.data, form.password.data, 3)
            if user is None:
                raise ValueError("用户名或密码错误")

            login_valid_errmsg = user.check_can_login()
            if not login_valid_errmsg == "":
                raise ValueError(login_valid_errmsg)

            login_user(user, form.remember_me.data)
            app.logger.info("后端用户[%s][%s]登入成功" % (user.email, user.nickname))
            # 直接跳转至需访问页面
            if session.get("login_next_url"):
                next_url = session.pop("login_next_url")
            else:
                next_url = url_for('backstage_management.index')
            return redirect(next_url)
        except Exception as e:
            app.logger.info("后端用户登入失败[%s]" % e)
            flash(e)
    else:
        form = AccountLoginForm(meta={'csrf_context': session})

    return render_template('backstage_management/account_login.html', form=form)


@backstage_management.route('/account/logout')
def account_logout():
    logout_user()
    return redirect(url_for('backstage_management.account_login'))


# 帐号信息管理
@backstage_management.route('/account/index')
def account_index():
    app.logger.info("into account_index")
    form = AccountForm(obj=current_user, user_type=current_user.get_user_type_name(), meta={'csrf_context': session})
    if len(current_user.user_infos) == 0:
        pass
    else:
        ui = current_user.user_infos[0]
        form.name.data = ui.name
        form.address.data = ui.address
        form.phone.data = ui.telephone
        form.title.data = ui.title

    if current_user.sales_areas.first() is not None:
        form.sale_range.data = ",".join([s.name for s in current_user.sales_areas.all()])
    if current_user.departments.first() is not None:
        form.dept_ranges.data = ",".join([d.name for d in current_user.departments.all()])

    return render_template('backstage_management/account_index.html', form=form)


# 帐号信息管理
@backstage_management.route('/account/password_update', methods=['POST'])
def account_password_update():
    app.logger.info("into account_password_update")
    try:
        form = BaseCsrfForm(request.form, meta={'csrf_context': session})
        if form.validate() is False:
            raise ValueError("非法提交,请通过正常页面进行修改")

        if request.form.get("email") != current_user.email:
            raise ValueError("非法提交,请通过正常页面进行修改")

        User.update_password(request.form.get("email"),
                             request.form.get("password_now"),
                             request.form.get("password_new"),
                             request.form.get("password_new_confirm"),
                             current_user.user_or_origin)

        flash("密码修改成功")
    except Exception as e:
        flash("密码修改失败: %s" % e)

    return redirect(url_for('backstage_management.account_index'))

application/design_application/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, flash, g, redirect, render_template, request, url_for, send_file
from flask_login import current_user
from flask.helpers import make_response
from .. import app, cache
from ..helpers import object_list, save_upload_file, delete_file
from ..models import DesignApplication, ProjectReport
from .forms import DesignApplicationForm
from ..wechat.models import WechatCall

design_application = Blueprint('design_application', __name__, template_folder='templates')


@design_application.route('/index')
def index():
    applications = DesignApplication.query.all()
    return render_template('design_application/index.html', applications=applications)


@design_application.route('/<int:id>/edit', methods=['GET', 'POST'])
def edit(id):
    application = DesignApplication.query.get_or_404(id)
    project_report = ProjectReport.query.filter_by(report_no=application.filing_no).first()
    if request.method == 'POST':
        form = DesignApplicationForm(request.form)
        form.populate_obj(application)
        if request.form.get('status') == '申请通过':
            if request.files.get('dl_file'):
                file_path = save_upload_file(request.files.get('dl_file'))
                if file_path:
                    if application.dl_file:
                        delete_file(application.dl_file)
                    application.dl_file = file_path
                else:
                    flash('%s文件格式不合法' % str(request.files.get('dl_file').filename), 'danger')
                    return redirect(url_for('design_application.index'))
            flash('申请通过 %s' % str(request.files.get('dl_file').filename), 'success')
        elif request.form.get('status') == '申请不通过':
            flash('申请不通过', 'warning')
        application.save
        cache.delete_memoized(current_user.get_new_design_application_num)
        WechatCall.send_template_to_user(str(application.applicant_id),
                                         "lW5jdqbUIcAwTF5IVy8iBzZM-TXMn1hVf9qWOtKZWb0",
                                         {
                                             "first": {
                                                 "value": "您的产品设计申请状态已更改",
                                                 "color": "#173177"
                                             },
                                             "keyword1": {
                                                 "value": application.filing_no,
                                                 "color": "#173177"
                                             },
                                             "keyword2": {
                                                 "value": application.status,
                                                 "color": "#173177"
                                             },
                                             "keyword3": {
                                                 "value": '',
                                                 "color": "#173177"
                                             },
                                             "remark": {
                                                 "value": "感谢您的使用！",
                                                 "color": "#173177"
                                             },
                                         },
                                         url_for('mobile_design_file', id=application.id)
                                         )
        return redirect(url_for('design_application.index'))
    else:
        form = DesignApplicationForm(obj=application)
    return render_template('design_application/edit.html', application=application, project_report=project_report,
                           form=form)


@design_application.route('/<int:id>/dl_file')
def dl_file(id):
    application = DesignApplication.query.get_or_404(id)
    response = make_response(send_file(app.config['APPLICATION_DIR'] + application.dl_file))
    response.headers['Content-Disposition'] = 'attachment; filename = %s' % application.dl_file.rsplit('/', 1)[1]
    return response


@design_application.route('/<int:id>/ul_file')
def ul_file(id):
    application = DesignApplication.query.get_or_404(id)
    response = make_response(send_file(app.config['APPLICATION_DIR'] + application.ul_file))
    response.headers['Content-Disposition'] = 'attachment; filename = %s' % application.ul_file.rsplit('/', 1)[1]
    return response

application/templates/design_application/edit.html
{% extends 'pc_base.html' %}
{% from 'macros/pc_partial.html' import sidebar with context %}
{% block main_content %}

{{ sidebar(active = 'design') }}
<div class="contents">
    <div class="contents-header">
        <div class="contents-header-img"><img class="full-img" src="/static/images/product.png" /></div>
        <p class="contents-header-p">产品设计申请详情</p>
        <p class="contents-header-p text-sm">details of design application</p>
    </div>
    <div class="separator"><span></span></div>

    <div class="widget">
        <div class="widget_header">
            <h4 class="widget_header_title"><span class="glyphicon glyphicon-th-large"></span>&nbsp;&nbsp;&nbsp;项目报备详情</h4>
        </div>
        <div class="widget_contents padding-0 bot-gap-2">
            <div class="form-item inline-2">
                <span class="form-label">报备编号</span>
                <input class="form-input form-control" value="{{ project_report.report_no }}" disabled/>
                <span class="form-label">创建日期</span>
                <input class="form-input form-control" value="{{ project_report.created_at.strftime('%Y-%m-%d') }}" disabled/>
                <span class="form-label">状态</span>
                <input class="form-input form-control" value="{{ project_report.status }}" disabled/>
            </div>
        </div>
        <div class="widget_contents padding-0">
            <table class="tables">
                <thead>
                    <tr>
                        <th>申请公司名称</th>
                        <th>项目跟进人</th>
                        <th>联系电话</th>
                        <th>联系传真</th>
                        <th>项目名称</th>
                        <th>项目报备日期</th>
                        <th>项目地址</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ project_report.report_content.get('app_company') }}</td>
                        <td>{{ project_report.report_content.get('project_follower') }}</td>
                        <td>{{ project_report.report_content.get('contract_phone') }}</td>
                        <td>{{ project_report.report_content.get('contract_fax') }}</td>
                        <td>{{ project_report.report_content.get('project_name') }}</td>
                        <td>{{ project_report.report_content.get('report_date') }}</td>
                        <td>{{ project_report.report_content.get('project_address') }}</td>
                    </tr>
                </tbody>
                <thead>
                    <tr>
                        <th>项目面积</th>
                        <th>产品使用场所</th>
                        <th>推荐产品系列</th>
                        <th>推荐产品颜色</th>
                        <th>项目完工时间</th>
                        <th>预计订购产品时间</th>
                        <th>竞争品牌情况</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ project_report.report_content.get('project_area') }}</td>
                        <td>{{ project_report.report_content.get('product_place') }}</td>
                        <td>{{ project_report.report_content.get('recommended_product_line') }}</td>
                        <td>{{ project_report.report_content.get('recommended_product_color') }}</td>
                        <td>{{ project_report.report_content.get('project_completion_time') }}</td>
                        <td>{{ project_report.report_content.get('expected_order_time') }}</td>
                        <td>{{ project_report.report_content.get('competitive_brand_situation') }}</td>
                    </tr>
                </tbody>
                <thead>
                    <tr>
                        <th>项目业主</th>
                        <th>项目装饰总包</th>
                        <th>项目设计公司</th>
                        <th>是否需要授权书</th>
                        <th>授权预计开具日期</th>
                        <th>需授权公司名称</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ project_report.report_content.get('project_owner') }}</td>
                        <td>{{ project_report.report_content.get('project_decoration_total') }}</td>
                        <td>{{ project_report.report_content.get('project_design_company') }}</td>
                        <td>{{ project_report.report_content.get('is_authorization_needed') }}</td>
                        <td>{{ project_report.report_content.get('expected_authorization_date') }}</td>
                        <td>{{ project_report.report_content.get('authorize_company_name') }}</td>
                        <td></td>
                    </tr>
                </tbody>
                <thead>
                    <tr>
                        <th>销售代表</th>
                        <th>销售主管</th>
                        <th>销售总监</th>
                        <th>是否开具授权</th>
                        <th>授权书日期</th>
                        <th>授权书编号</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ project_report.audit_content.get('sales_representative') }}</td>
                        <td>{{ project_report.audit_content.get('sales_executive') }}</td>
                        <td>{{ project_report.audit_content.get('sales_director') }}</td>
                        <td>{{ project_report.audit_content.get('is_authorized') }}</td>
                        <td>{{ project_report.audit_content.get('authorization_date') }}</td>
                        <td>{{ project_report.audit_content.get('authorization_no') }}</td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="widget top-gap-2">
        <div class="widget_header">
            <h4 class="widget_header_title"><span class="glyphicon glyphicon-th-large"></span>&nbsp;&nbsp;&nbsp;产品设计申请详情</h4>
        </div>
        <div class="widget_contents padding-0 bot-gap-3">
            <div class="form-item inline-2">
                <span class="form-label">申请日期</span>
                <input class="form-input form-control" value="{{ application.created_at.strftime('%F') }}" disabled/>
                <span class="form-label">经销商</span>
                <input class="form-input form-control" value="{{ application.applicant.nickname }}" disabled/>
                <span class="form-label">经销商所属区域</span>
                <input class="form-input form-control" value="{{ application.applicant.sales_areas.all()[0].name }}" disabled/>
            </div>
            <div class="form-item">
                <span class="form-label">设计图纸<br>(微信端上传)</span>
                <a href="{{ url_for('design_application.ul_file', id = application.id) }}" class="btn btn-info">点击下载</a>
            </div>
        </div>

        <div class="widget_header">
            <h4 class="widget_header_title"><span class="glyphicon glyphicon-th-large"></span>&nbsp;&nbsp;&nbsp;申请审批</h4>
        </div>
        
        <form action="{{ url_for('design_application.edit', id = application.id) }}" enctype="multipart/form-data" method="post">
            <div class="widget_contents padding-0">
                <div class="form-item">
                    <span class="form-label">{{ form.status.label }}</span>
                    {{ form.status(class='form-input form-control')}}
                </div>
                <div class="form-item">
                    <span class="form-label">上传设计文件<br>(微信端下载)</span>
                    <input name="dl_file" class="form-input form-control" type="file"/>
                </div>
                <div class="form-item">
                    <span class="form-label">{{ form.dl_file_memo.label }}</span>
                    {{ form.dl_file_memo(class='form-input form-control', placeholder='申请审批或上传设计文件时填写的备注, 不超过200字') }}
                </div>
            </div>
            <div class="text-right top-gap-1">
                <a href="{{ url_for('design_application.index') }}" class="btn btn-default my-btn">返回</a>
                <button type="submit" class="btn btn-default my-btn" data-disable-with="Please wait...">提交</button>     
            </div>
        </form>

    </div>
</div>

{% endblock %}

application/templates/design_application/index.html
{% extends 'pc_base.html' %}
{% from 'macros/pc_partial.html' import sidebar with context %}
{% block main_content %}

{{ sidebar(active = 'design') }}
<div class="contents">
    <div class="contents-header">
        <div class="contents-header-img"><img class="full-img" src="/static/images/product.png" /></div>
        <p class="contents-header-p">产品设计申请列表</p>
        <p class="contents-header-p text-sm">list of design applications</p>
    </div>
    <div class="separator"><span></span></div>
    <form url="{{ url_for('design_application.index') }}" method="get" role="form" class="form form-horizontal" >
        <div class="form-style form-default">
            <div class="form-item-2 col-3">
                <span>从</span>
                <input class="form-control datetimePicker" name="from">
            </div>
            <div class="form-item-2 col-3">
                <span>到</span>
                <input class="form-control datetimePicker" name="to">
            </div>
            <div class="form-item-2 col-3">
                <span>报备编号</span>
                <input class="form-control" name="filing_no">
            </div>
            <div class="form-item-2 col-3">
                <span>申请状态</span>
                <select class="form-control" name="order_status"></select>
            </div>
            <div class="clearfix"></div>
            <div class="text-right top-gap-2 right-gap-3">
                <button class="btn btn-default my-btn">筛选条件</button>
            </div>
        </div>
    </form>

    <div class="widget">
        <div class="widget_header">
            <h4 class="widget_header_title"><span class="glyphicon glyphicon-th-large"></span>&nbsp;&nbsp;&nbsp;物料申请列表</h4>
        </div>
        <div class="widget_contents padding-0">
            <table class="tables">
                <thead>
                    <tr>
                        <th>报备编号</th>
                        <th>申请日期</th>
                        <th>申请状态</th>
                        <th>设计图纸(微信端上传)</th>
                        <th>设计文件(微信端下载)</th>
                    </tr>
                </thead>
                <tbody>
                    {% for application in applications %}
                    <tr>
                        <td><a href="{{ url_for('design_application.edit', id = application.id) }}" class="table-link">{{ application.filing_no }}</a></td>
                        <td>{{ application.created_at.strftime('%F') }}</td>
                        <td><span class="text-warning">{{ application.status }}</span></td>
                        <td><a href="{{ url_for('design_application.ul_file', id = application.id) }}">点击下载</a></td>
                        <td>
                        {% if application.status == '申请通过' and application.dl_file %}
                            <a href="{{ url_for('design_application.dl_file', id = application.id) }}">点击下载</a>
                        {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}