application/design_application/forms.py
# -*- coding: utf-8 -*-
from wtforms import Form, StringField, SelectField, TextAreaField
from wtforms.validators import *


class DesignApplicationForm(Form):
    status = SelectField('申请状态', choices=[('新申请', '新申请'), ('申请通过', '申请通过'), ('申请不通过', '申请不通过')])
    dl_file_memo = TextAreaField('备注')

application/product/forms.py
# -*- coding: utf-8 -*-
import wtforms
from wtforms.validators import *

application/__init__.py
# -*- coding: utf-8 -*-
import os
from flask import Flask, g, render_template, redirect, url_for, request, flash
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from .utils import num2moneyformat

from .config import config
from flask_cache import Cache

import logging

app = Flask(__name__)
app.config.from_object(config[os.getenv('FLASK_ENV') or 'default'])
db = SQLAlchemy(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "backstage_management.account_login"

bcrypt = Bcrypt(app)
cache = Cache(app, config={'CACHE_TYPE': 'simple'})

from .content.views import content

app.register_blueprint(content, url_prefix='/content')
from .product.views import product

app.register_blueprint(product, url_prefix='/product')
from .order_manage.views import order_manage

app.register_blueprint(order_manage, url_prefix='/order_manage')
from .inventory.views import inventory

app.register_blueprint(inventory, url_prefix='/inventory')
from .wechat.views import wechat

app.register_blueprint(wechat, url_prefix='/wechat')
from .design_application.views import design_application

app.register_blueprint(design_application, url_prefix='/design_application')
from .project_report.views import project_report

app.register_blueprint(project_report, url_prefix='/project_report')
from .organization.views import organization

app.register_blueprint(organization, url_prefix='/organization')
from .web_access_log.views import web_access_log

app.register_blueprint(web_access_log, url_prefix='/web_access_log')

from .backstage_management.views import backstage_management

app.register_blueprint(backstage_management, url_prefix='/backstage_management')

from .inventory.api import load_products, load_skus, load_inventories_by_code

app.add_template_global(load_products)
app.add_template_global(load_skus)
app.add_template_global(load_inventories_by_code)
app.add_template_global(len)
app.add_template_global(int)
app.add_template_global(str)
app.add_template_global(num2moneyformat)


@app.before_first_request
def setup_logging():
    if not app.debug:
        # In production mode, add log handler to sys.stderr.
        app.logger.addHandler(logging.StreamHandler())
        app.logger.setLevel(logging.INFO)
        app.logger.info("RUN ENV : [%s]" % os.getenv('FLASK_ENV'))


@app.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404


@app.errorhandler(500)
def internal_server_error(error):
    return render_template('500.html'), 500


@app.route('/')
def root():
    return redirect(url_for('mobile_index'))


@app.route('/admin')
def admin():
    return redirect(url_for('backstage_management.index'))

application/design_application/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, flash, g, redirect, render_template, request, url_for, send_file
from flask_login import current_user
from flask.helpers import make_response
from .. import app, cache
from ..helpers import object_list, save_upload_file, delete_file
from ..models import DesignApplication, ProjectReport
from .forms import DesignApplicationForm
from ..wechat.models import WechatCall

design_application = Blueprint('design_application', __name__, template_folder='templates')


@design_application.route('/index')
def index():
    applications = DesignApplication.query.all()
    return render_template('design_application/index.html', applications=applications)


@design_application.route('/<int:id>/edit', methods=['GET', 'POST'])
def edit(id):
    application = DesignApplication.query.get_or_404(id)
    project_report = ProjectReport.query.filter_by(report_no=application.filing_no).first()
    if request.method == 'POST':
        form = DesignApplicationForm(request.form)
        form.populate_obj(application)
        if request.form.get('status') == '申请通过':
            if request.files.get('dl_file'):
                file_path = save_upload_file(request.files.get('dl_file'))
                if file_path:
                    if application.dl_file:
                        delete_file(application.dl_file)
                    application.dl_file = file_path
                else:
                    flash('%s文件格式不合法' % str(request.files.get('dl_file').filename), 'danger')
                    return redirect(url_for('design_application.index'))
            flash('申请通过 %s' % str(request.files.get('dl_file').filename), 'success')
        elif request.form.get('status') == '申请不通过':
            flash('申请不通过', 'warning')
        application.save
        cache.delete_memoized(current_user.get_new_design_application_num)
        WechatCall.send_template_to_user(str(application.applicant_id),
                                         "lW5jdqbUIcAwTF5IVy8iBzZM-TXMn1hVf9qWOtKZWb0",
                                         {
                                             "first": {
                                                 "value": "您的产品设计申请状态已更改",
                                                 "color": "#173177"
                                             },
                                             "keyword1": {
                                                 "value": application.filing_no,
                                                 "color": "#173177"
                                             },
                                             "keyword2": {
                                                 "value": application.status,
                                                 "color": "#173177"
                                             },
                                             "keyword3": {
                                                 "value": '',
                                                 "color": "#173177"
                                             },
                                             "remark": {
                                                 "value": "感谢您的使用！",
                                                 "color": "#173177"
                                             },
                                         },
                                         url_for('mobile_design_file', id=application.id)
                                         )
        return redirect(url_for('design_application.index'))
    else:
        form = DesignApplicationForm(obj=application)
    return render_template('design_application/edit.html', application=application, project_report=project_report,
                           form=form)


@design_application.route('/<int:id>/dl_file')
def dl_file(id):
    application = DesignApplication.query.get_or_404(id)
    response = make_response(send_file(app.config['APPLICATION_DIR'] + application.dl_file))
    response.headers['Content-Disposition'] = 'attachment; filename = %s' % application.dl_file.rsplit('/', 1)[1]
    return response


@design_application.route('/<int:id>/ul_file')
def ul_file(id):
    application = DesignApplication.query.get_or_404(id)
    response = make_response(send_file(app.config['APPLICATION_DIR'] + application.ul_file))
    response.headers['Content-Disposition'] = 'attachment; filename = %s' % application.ul_file.rsplit('/', 1)[1]
    return response

application/product/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, flash, redirect, render_template, request, url_for
from .. import db
from ..helpers import save_upload_file, delete_file, clip_image
from .api import *
from ..models import Content, ContentCategory

product = Blueprint('product', __name__, template_folder='templates')

product_image_size = (379, 226)
sku_image_size = (290, 290)


@product.route('/index/<int:category_id>')
def index(category_id):
    products = load_products(category_id, only_valid=False)
    category = load_category(category_id)
    return render_template('product/index.html', products=products, category=category)


@product.route('/new/<int:category_id>', methods=['GET', 'POST'])
def new(category_id):
    if request.method == 'POST':
        option_ids = request.form.getlist('option_ids[]')
        image_files = [request.files.get('image_file_0'), request.files.get('image_file_1')]
        product_image_links = []
        for image_file in image_files:
            if image_file:
                image_path = save_upload_file(image_file)
                if image_path:
                    clip_image((app.config['APPLICATION_DIR'] + image_path), size=product_image_size)
            else:
                image_path = ''
            product_image_links.append(image_path)
        product_info = {
            'name': request.form.get('name'),
            'code': request.form.get('code'),
            'length': request.form.get('length'),
            'width': request.form.get('width'),
            'description': request.form.get('description'),
            'product_image_links': product_image_links,
            'case_ids': [],
            'options_id': [str(option_id) for option_id in option_ids]
        }
        data = {
            'product_category_id': str(category_id),
            'product_info': product_info
        }
        response = create_product(data)
        if response.status_code == 201:
            return redirect(url_for('product.sku_index', product_id=int(response.json().get('product_id'))))
        return redirect(url_for('product.index', category_id=category_id))
    category = load_category(category_id)
    features = load_features()
    return render_template('product/new.html', category=category, features=features)


@product.route('/relate_cases/<int:product_id>', methods=['GET', 'POST'])
def relate_cases(product_id):
    _product = load_product(product_id)
    contents = ContentCategory.query.filter(ContentCategory.name == '案例展示').first().contents
    if request.method == 'POST':
        case_ids = [int(case_id) for case_id in request.form.getlist('case_ids[]')]
        data = {'case_ids': case_ids}
        response = update_product(_product.get('product_id'), data=data)
        if response.status_code == 200:
            for content in contents:
                if content.id in case_ids:
                    if product_id not in content.product_ids:
                        temp = list(content.product_ids)
                        temp.append(product_id)
                        content.product_ids = temp
                        db.session.add(content)
                else:
                    if product_id in content.product_ids:
                        temp = list(content.product_ids)
                        temp.remove(product_id)
                        content.product_ids = temp
                        db.session.add(content)
            db.session.commit()
            flash('关联案例修改成功', 'success')
        else:
            flash('关联案例修改失败', 'danger')
        return redirect(url_for('product.category_index'))
    return render_template('product/relate_cases.html', product=_product, contents=contents)


@product.route('/<int:id>')
def show(id):
    category = load_category(request.args.get('category_id'))
    _product = load_product(id, option_sorted=True)
    skus = load_skus(id)
    contents = Content.query.filter(Content.id.in_(_product.get('case_ids')))
    option_sorted = _product.get('option_sorted')
    return render_template('product/show.html', category=category, product=_product, skus=skus, contents=contents,
                           option_sorted=option_sorted)


@product.route('/<int:id>/edit', methods=['GET', 'POST'])
def edit(id):
    category_id = request.args.get('category_id')
    if not category_id:
        return redirect(url_for('product.category_index'))
    _product = load_product(id)
    category = load_category(category_id)
    features = load_features()
    option_ids = [x.get('option_id') for x in load_product_options(_product.get('product_id')).get('options')]
    if request.method == 'POST':
        option_ids = request.form.getlist('option_ids[]')
        product_image_links = _product.get('images') or []
        if request.files:
            for param in request.files:
                if 'image_file' in param and request.files.get(param):
                    _index = int(param.rsplit('_', 1)[1])
                    if len(product_image_links) < _index + 1:
                        for i in range(_index+1-len(product_image_links)):
                            product_image_links.append('')
                    image_path = save_upload_file(request.files.get(param))
                    if image_path:
                        clip_image((app.config['APPLICATION_DIR'] + image_path), size=product_image_size)
                        if product_image_links[_index]:
                            delete_file(product_image_links[_index])
                        product_image_links[_index] = image_path
        data = {
            'name': request.form.get('name'),
            'length': request.form.get('length'),
            'width': request.form.get('width'),
            'description': request.form.get('description'),
            'product_image_links': product_image_links,
            'options_id': [str(option_id) for option_id in option_ids],
            'isvalid': request.form.get('isvalid')
        }
        response = update_product(id, data=data)
        if response.status_code == 200:
            flash('产品修改成功', 'success')
        else:
            flash('产品修改失败: %s' % response.json(), 'danger')
        return redirect(url_for('product.index', category_id=category_id))
    return render_template('product/edit.html', product=_product, category=category, features=features,
                           option_ids=option_ids)


@product.route('/<int:id>/delete', methods=['POST'])
def delete(id):
    if request.method == 'POST':
        category_id = request.args.get('category_id')
        response = delete_product(id)
        if response.status_code == 200:
            flash('产品删除成功', 'success')
        else:
            flash('产品删除失败', 'danger')
        if category_id:
            return redirect(url_for('product.index', category_id=category_id))
        return redirect(url_for('product.category_index'))


@product.route('/sku/index/<int:product_id>')
def sku_index(product_id):
    skus = load_skus(product_id)
    # _product = load_product(product_id)
    features = load_features()
    option_ids = [x.get('option_id') for x in load_product_options(product_id).get('options')]
    return render_template('product/sku/index.html', skus=skus, product_id=product_id,
                           features=features, option_ids=option_ids)


@product.route('/sku/new/<int:product_id>', methods=['GET', 'POST'])
def sku_new(product_id):
    if request.method == 'POST':
        option_ids = request.form.getlist('option_ids[]')
        image_file = request.files.get('image_file')
        if image_file:
            image_path = save_upload_file(image_file)
            if image_path:
                clip_image((app.config['APPLICATION_DIR'] + image_path), size=sku_image_size)
        else:
            image_path = ''
        sku_infos = []
        sku_info = {
            'code': request.form.get('code'),
            'barcode': request.form.get('barcode') or None,
            'hscode': request.form.get('hscode') or None,
            'weight': request.form.get('weight') or None,
            'thumbnail': image_path,
            'name': request.form.get('name') or None,
            'memo': request.form.get('memo') or None,
            'options_id': [str(option_id) for option_id in option_ids]
        }
        sku_infos.append(sku_info)
        data = {
            'product_id': str(product_id),
            'sku_infos': sku_infos
        }
        response = create_sku(data)
        if response.status_code == 201:
            flash('SKU创建成功', 'success')
        else:
            flash('SKU创建失败', 'danger')
        return redirect(url_for('product.sku_index', product_id=product_id))
    _product = load_product(product_id, option_sorted=True)
    option_sorted = _product.get('option_sorted')
    return render_template('product/sku/new.html', product=_product, option_sorted=option_sorted)


@product.route('/sku/<int:id>/edit', methods=['GET', 'POST'])
def sku_edit(id):
    product_id = request.args.get('product_id')
    if not product_id:
        return redirect(url_for('product.category_index'))
    sku = load_sku(product_id=product_id, sku_id=id)
    if request.method == 'POST':
        option_ids = []
        for option_id in request.form.getlist('option_ids[]'):
            if option_id:
                option_ids.append(option_id)
        image_file = request.files.get('image_file')
        if image_file:
            image_path = save_upload_file(image_file)
            if image_path:
                clip_image((app.config['APPLICATION_DIR'] + image_path), size=sku_image_size)
                if sku.get('thumbnail'):
                    delete_file(sku.get('thumbnail'))
        else: 
            image_path = sku.get('thumbnail')
        data = {
            'barcode': request.form.get('barcode'),
            'hscode': request.form.get('hscode'),
            'weight': request.form.get('weight') or None,
            'isvalid': request.form.get('isvalid'),

application/templates/product/sku/batch_new.html
{% extends 'pc_base.html' %}
{% from 'macros/pc_partial.html' import sidebar with context %}
{% block main_content %}

{{ sidebar(active = 'product') }}

<div class="contents">
	<div class="contents-header">
		<div class="contents-header-img"><img class="full-img" src="/static/images/product.png" /></div>
		<p class="contents-header-p">批量创建sku</p>
		<p class="contents-header-p text-sm">batch new sku</p>
	</div>
	<div class="separator"><span></span></div>

	<form action="{{ url_for('product.sku_batch_new', product_id = product.get('product_id')) }}" enctype="multipart/form-data" method="post">
	<input name="sku_count" value="{{ option_combinations | length }}" type="hidden">
	{% for combination in option_combinations %}
	{% set index = option_combinations.index(combination) %}

		<div class="widget">
			<div class="widget_header">
				<h4 class="widget_header_title"><span class="glyphicon glyphicon-off"></span>&nbsp;&nbsp;&nbsp;
				{% for option in combination %}{{ option.get('feature_name') }}:{{ option.get('option_name') }}/{% endfor %}</h4>
			</div>
			<div class="widget_contents padding-0">
				{% for option in combination %}
					<input name="{{ index }}_option_ids[]" value="{{ option.get('option_id') }}" type="hidden" id="option_{{ option.get('option_id') }}" /> 
				{% endfor %}
			
				<div class="form-item inline-2">
					<span class="form-label">sku代码</span>
					<input class="form-input form-control" name="{{ index }}_code"/>
					<span class="form-label">价格</span>
					<input class="form-input form-control" name="{{ index }}_price"/>
				</div>
				<div class="form-item inline-2">
					<span class="form-label">库存</span>
					<input class="form-input form-control" name="{{ index }}_stocks"/>
					<span class="form-label">Barcode</span>
					<input class="form-input form-control" name="{{ index }}_barcode"/>
				</div>
				<div class="form-item inline-2">
					<span class="form-label">hscode</span>
					<input class="form-input form-control" name="{{ index }}_hscode"/>
					<span class="form-label">重量</span>
					<input class="form-input form-control" name="{{ index }}_weight"/>
				</div>
				<div class="form-item small-pic">
					<span class="form-label">产品图片</span>
					<div class="pic-upload top-gap-1">
						<input type="file" name="{{ index }}_image_file" id="image_file" class="inbox-file">
						<img class="full-img" src="/static/images/alt.jpg">
					</div>
				</div>
			</div>
		</div>

	{% endfor %}

		<div class="text-right top-gap-1">
			<a class="btn btn-default my-btn right-gap-1" href="javascript:history.go(-1);">返回</a>
			<button class="btn btn-default my-btn">提交</button>
		</div>
	</form>
	
</div>

{% endblock %}

application/templates/product/sku/edit.html
{% extends 'pc_base.html' %}
{% from 'macros/pc_partial.html' import sidebar with context %}
{% block main_content %}

{{ sidebar(active = 'product') }}

<div class="contents">
	<div class="contents-header">
		<div class="contents-header-img"><img class="full-img" src="/static/images/product.png" /></div>
		<p class="contents-header-p">编辑sku</p>
		<p class="contents-header-p text-sm">edit sku</p>
	</div>
	<div class="separator"><span></span></div>

	<form action="{{ url_for('product.sku_edit', id = sku.get('sku_id'), product_id = product.get('product_id')) }}" enctype="multipart/form-data" method="post">
		<div class="widget">
			<div class="widget_header">
				<h4 class="widget_header_title"><span class="glyphicon glyphicon-off"></span>&nbsp;&nbsp;&nbsp;{{ product.get('name') }}</h4>
			</div>
			<div class="widget_contents padding-0">

				<div class="form-item inline-2">
					{% for option in option_set %}
						<span class="form-label">{{ option[0] }}</span>
						<input class="form-input form-control" name="code" value="{{ option[1] }}" disabled=""/>
					{% endfor %}
					<a class="new-item" onclick="$('#edit_options_form').toggle();"><span class="glyphicon glyphicon-edit"></span></a>
				</div>

				<div id="edit_options_form" class="form-item inline-2" style="display: none; background: #eee;">
					{% for options in option_sorted %}
					<div class="col-3" style="display:table; margin:10px 0px; ">
						<span class="form-label">{{ options[0].get('feature_name') }}</span>
						<select name="option_ids[]" class="form-input form-control">
							<option	value=""></option>
							{% for option in options %}
								<option value="{{ option.get('option_id') }}">{{ option.get('option_name') }}</option>
							{% endfor %}
						</select>
					</div>
					{% endfor %}
				</div>

				<div class="form-item inline-2">
					<span class="form-label">sku代码</span>
					<input class="form-input form-control" name="code" value="{{ sku.get('code') or '' }}" required/>
					<span class="form-label">名称</span>
					<input class="form-input form-control" name="name" value="{{ sku.get('name') or '' }}"/>
				</div>
				<div class="form-item inline-2">
					<span class="form-label">Barcode</span>
					<input class="form-input form-control" name="barcode" value="{{ sku.get('barcode') or '' }}"/>
					<span class="form-label">hscode</span>
					<input class="form-input form-control" name="hscode" value="{{ sku.get('hscode') or '' }}"/>
				</div>
				<div class="form-item inline-2">
					<span class="form-label">重量(g/m2)</span>
					<input class="form-input form-control" name="weight" value="{{ sku.get('weight') or '' }}" required/>
					<span class="form-label">备注</span>
					<input class="form-input form-control" name="memo" value="{{ sku.get('memo') or '' }}"/>
				</div>
				<div class="form-item inline-2">
					<span class="form-label">状态</span>
					<select name="isvalid" id="isvalid" class="form-input form-control">
						<option value="YES">上架</option>
						<option value="NO" {{ 'selected' if sku.get('isvalid') == 'NO' else '' }}>下架</option>
					</select>
				</div>
				<div class="form-item small-pic">
					<span class="form-label">产品图片</span>
					<div class="pic-upload top-gap-1">
						<input type="file" name="image_file" id="image_file" class="inbox-file">
						<img class="full-img" src="{{ sku.get('thumbnail') }}">
					</div>
				</div>
			</div>
		</div>

		<div class="text-right top-gap-1">
			<a class="btn btn-default my-btn right-gap-1" href="javascript:history.go(-1);">返回</a>
			<button class="btn btn-default my-btn">提交</button>
		</div>
	</form>
	
</div> 

{% endblock %}

application/templates/product/sku/index.html
{% extends 'pc_base.html' %}
{% from 'macros/pc_partial.html' import sidebar with context %}
{% block main_content %}

{{ sidebar(active = 'product') }}

<div class="contents">
	<div class="contents-header">
		<div class="contents-header-img"><img class="full-img" src="/static/images/product.png" /></div>
		<p class="contents-header-p">SKU列表</p>
		<p class="contents-header-p text-sm">skus list</p>
		<a class="new-one" href="{{ url_for('product.sku_new', product_id = product_id) }}"><span class="glyphicon glyphicon-plus"></span></a>
	</div>
	<div class="separator"><span></span></div>
	<div class="widget">
		<div class="widget_header">
			<h4 class="widget_header_title"><span class="glyphicon glyphicon-th-large"></span>
				&nbsp;&nbsp;&nbsp;<a>{{ skus.get('name') }}</a>
			</h4>
			<a class="new-item" onclick="$('#feature_wrapper').slideToggle();"><span class="glyphicon glyphicon-th"></span></a>
		</div>
		<div id="feature_wrapper" class="widget_contents padding-0" style="display: none; border-bottom: 0; border-radius: 0;">
			{% for feature in features %}
				<div class="form-item">
					<span class="form-label">{{ feature.get('feature_name') }}</span>
					<div class="label-block">
					{% for option in feature.get('options')|sort(attribute='option_name') %}
						<div class="label-item">
							<input name="option_ids[]" value="{{ option.get('option_id') }}" type="checkbox" id="option_{{ option.get('option_id') }}" class="chk_1"
							{% if option.get('option_id') in option_ids %}checked=""{% endif %} disabled/>
							<label for="option_{{ option.get('option_id') }}">{{ option.get('option_name') }}</label>
						</div>
					{% endfor %}
					</div>
				</div>
			{% endfor %}
		</div>

		<div class="widget_contents padding-0">
			<table class="tables">
				<thead>
					<tr>
						<th>SKU code</th>
						<th>名称</th>
						<th>Barcode</th>
						<th>HScode</th>
						<th>重量</th>
						<th>状态</th>
						<th>属性</th>
						<th>备注</th>
						<th>操作</th>
					</tr>
				</thead>
				<tbody>
				{% for sku in skus.get('skus') %}
					<tr>
						<td>{{ sku.get('code') }}</td>
						<td>{{ sku.get('name') or '-' }}</td>
						<td>{{ sku.get('barcode') or '-' }}</td>
						<td>{{ sku.get('hscode') or '-' }}</td>
						<td>{{ sku.get('weight') or '-' }} g/m2</td>
						{% if sku.get('isvalid') == 'NO' %}
							<td class="state invalid">{{ '下架' }}</td>
						{% else %}
							<td class="state valid">{{ '上架' }}</td>
						{% endif %}
						<td>
						{% for option in sku.get('options') %}
							{% for key in option %}{{ key }}:{{ option[key] }}{% endfor %}&nbsp;&nbsp;
						{% endfor %}
						</td>
						<td>{{ sku.get('memo') or '' }}</td>
						<td>
							<a class="table-edit text-info" href="{{ url_for('product.sku_edit', id = sku.get('sku_id'), product_id = product_id) }}"><span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;编辑</a>
							<form action="{{ url_for('product.sku_delete', id = sku.get('sku_id'), product_id = product_id) }}" method="post" style="display: inline;">
								<button type="submit" data-confirm="确定删除SKU[ {{ sku.get('code') }} ]？" data-confirmType="post" class="btn-link table-del" style="color: #843534; text-decoration: none; "><span class="glyphicon glyphicon-remove"></span>&nbsp;&nbsp;删除</button>
							</form>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>

		<div class="text-right top-gap-1">
			<a class="btn btn-default my-btn right-gap-1" href="javascript:history.go(-1);">返回</a>
		</div>
	</div>
</div>

{% endblock %}

application/templates/product/sku/new.html
{% extends 'pc_base.html' %}
{% from 'macros/pc_partial.html' import sidebar with context %}
{% block main_content %}

{{ sidebar(active = 'product') }}

<div class="contents">
	<div class="contents-header">
		<div class="contents-header-img"><img class="full-img" src="/static/images/product.png" /></div>
		<p class="contents-header-p">新增sku</p>
		<p class="contents-header-p text-sm">new sku</p>
	</div>
	<div class="separator"><span></span></div>

	<form action="{{ url_for('product.sku_new', product_id = product.get('product_id')) }}" enctype="multipart/form-data" method="post">
		<div class="widget">
			<div class="widget_header">
				<h4 class="widget_header_title"><span class="glyphicon glyphicon-off"></span>&nbsp;&nbsp;&nbsp;{{ product.get('name') }}</h4>
			</div>
			<div class="widget_contents padding-0">

				<div class="form-item inline-2">
					{% for options in option_sorted %}
					<div class="col-3" style="display:table; margin:10px 0px;">
						<span class="form-label">{{ options[0].get('feature_name') }}</span>
						<select name="option_ids[]" class="form-input form-control">
							<option value=""></option>
							{% for option in options %}
								<option value="{{ option.get('option_id') }}">{{ option.get('option_name') }}</option>
							{% endfor %}
						</select>
					</div>
					{% endfor %}
				</div>

				<div class="form-item inline-2">
					<span class="form-label">sku代码</span>
					<input class="form-input form-control" name="code" required/>
					<span class="form-label">名称</span>
					<input class="form-input form-control" name="name"/>
				</div>
				<div class="form-item inline-2">
					<span class="form-label">Barcode</span>
					<input class="form-input form-control" name="barcode"/>
					<span class="form-label">hscode</span>
					<input class="form-input form-control" name="hscode"/>
				</div>
				<div class="form-item inline-2">
					<span class="form-label">重量(g/m2)</span>
					<input class="form-input form-control" name="weight" required/>
					<span class="form-label">备注</span>
					<input class="form-input form-control" name="memo"/>
				</div>
				<div class="form-item small-pic">
					<span class="form-label">产品图片</span>
					<div class="pic-upload top-gap-1">
						<input type="file" name="image_file" id="image_file" class="inbox-file">
						<img class="full-img" src="/static/images/alt.jpg">
					</div>
				</div>
			</div>
		</div>

		<div class="text-right top-gap-1">
			<a class="btn btn-default my-btn right-gap-1" href="javascript:history.go(-1);">返回</a>
			<button class="btn btn-default my-btn">提交</button>
		</div>
	</form>
	
</div>

{% endblock %}